/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import javax.swing.JFrame;

/**
 *
 * @author letha
 */
public class ManHinhChinh extends JFrame  {

    //private static final long serialVersionUID = 1L;
	/**
     * Creates new form Main
     */
    public ManHinhChinh() {
    		initComponents();
                khoaflag(false);
                setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    private void excute(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTieuDe = new javax.swing.JPanel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblTenTieuDe = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnDMSanPham = new javax.swing.JButton();
        btnLapHoaDon = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnSach = new javax.swing.JButton();
        btnDSHoaDon = new javax.swing.JButton();
        btnQLNhanVien = new javax.swing.JButton();
        btnDangKyCa = new javax.swing.JButton();
        btnDSNhanVien = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnTKDoanhThu = new javax.swing.JButton();
        btnTKSanPham = new javax.swing.JButton();
        btnTKKhachHang = new javax.swing.JButton();
        btnNhaCungCap = new javax.swing.JButton();
        btnDSNhaCungCap = new javax.swing.JButton();
        btnNhapHang = new javax.swing.JButton();
        btnTacGia = new javax.swing.JButton();
        btnTimKiemNCC = new javax.swing.JButton();
        btnDSKhachHang = new javax.swing.JButton();
        btnTimKiemNV = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        btnHoTro = new javax.swing.JButton();
        btnDSTacGai = new javax.swing.JButton();
        btnTimKiemTG = new javax.swing.JButton();
        btnNXB = new javax.swing.JButton();
        btnDanhSachNXB = new javax.swing.JButton();
        btnTimKiemNXB = new javax.swing.JButton();
        btnTimKiemSach = new javax.swing.JButton();
        btnSanPhamKhac = new javax.swing.JButton();
        btnTimKiemSPKhac = new javax.swing.JButton();
        btnTimKiemKH = new javax.swing.JButton();
        btnLoaiSP = new javax.swing.JButton();
        btnDSLoaiSP = new javax.swing.JButton();
        btnTimKiemLSP = new javax.swing.JButton();
        pnlChuongTrinh = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTieuDe.setBackground(new java.awt.Color(153, 153, 153));

        lblTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        lblTaiKhoan.setText("Admin");

        lblTenTieuDe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenTieuDe.setText("Hệ thống cửa hàng sách tư nhân");

        lblDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N

        javax.swing.GroupLayout pnlTieuDeLayout = new javax.swing.GroupLayout(pnlTieuDe);
        pnlTieuDe.setLayout(pnlTieuDeLayout);
        pnlTieuDeLayout.setHorizontalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTieuDeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 556, Short.MAX_VALUE)
                .addComponent(lblTenTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398)
                .addComponent(lblDangXuat)
                .addGap(77, 77, 77))
        );
        pnlTieuDeLayout.setVerticalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDangXuat)
                    .addGroup(pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTenTieuDe)))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pnlMenu.setBackground(new java.awt.Color(204, 204, 204));

        btnDMSanPham.setBackground(new java.awt.Color(255, 102, 0));
        btnDMSanPham.setText("Sản phẩm");
        btnDMSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDMSanPhamMouseClicked(evt);
            }
        });
        btnDMSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMSanPhamActionPerformed(evt);
            }
        });

        btnLapHoaDon.setText("Lập hóa đơn");
        btnLapHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapHoaDonActionPerformed(evt);
            }
        });

        btnHoaDon.setBackground(new java.awt.Color(255, 102, 0));
        btnHoaDon.setText("Hóa đơn");
        btnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseClicked(evt);
            }
        });

        btnSach.setText("Sách");
        btnSach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSach.setDefaultCapable(false);
        btnSach.setHideActionText(true);
        btnSach.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSachActionPerformed(evt);
            }
        });

        btnDSHoaDon.setText("Danh sách hóa đơn");
        btnDSHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSHoaDonActionPerformed(evt);
            }
        });

        btnQLNhanVien.setBackground(new java.awt.Color(255, 102, 0));
        btnQLNhanVien.setText("Nhân viên");
        btnQLNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLNhanVienMouseClicked(evt);
            }
        });

        btnDangKyCa.setText("Đăng ký ca");
        btnDangKyCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyCaActionPerformed(evt);
            }
        });

        btnDSNhanVien.setText("Danh sách nhân viên");
        btnDSNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSNhanVienActionPerformed(evt);
            }
        });

        btnKhachHang.setBackground(new java.awt.Color(255, 102, 0));
        btnKhachHang.setText("Khách hàng");
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseClicked(evt);
            }
        });

        btnTKDoanhThu.setText("Thống kê doanh thu");
        btnTKDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTKDoanhThuMouseClicked(evt);
            }
        });
        btnTKDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKDoanhThuActionPerformed(evt);
            }
        });

        btnTKSanPham.setText("Thống kê sản phẩm");
        btnTKSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKSanPhamActionPerformed(evt);
            }
        });

        btnTKKhachHang.setText("Thống kê khách hàng");
        btnTKKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKKhachHangActionPerformed(evt);
            }
        });

        btnNhaCungCap.setBackground(new java.awt.Color(255, 102, 0));
        btnNhaCungCap.setText("Nhà cung cấp");
        btnNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhaCungCapMouseClicked(evt);
            }
        });
        btnNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCapActionPerformed(evt);
            }
        });

        btnDSNhaCungCap.setText("Danh sách");
        btnDSNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSNhaCungCapActionPerformed(evt);
            }
        });

        btnNhapHang.setText("Nhập hàng");
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });

        btnTacGia.setBackground(new java.awt.Color(255, 102, 0));
        btnTacGia.setText("Tác giả");
        btnTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTacGiaMouseClicked(evt);
            }
        });
        btnTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacGiaActionPerformed(evt);
            }
        });

        btnTimKiemNCC.setText("Tìm kiếm");
        btnTimKiemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemNCCActionPerformed(evt);
            }
        });

        btnDSKhachHang.setText("Danh sách");
        btnDSKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSKhachHangActionPerformed(evt);
            }
        });

        btnTimKiemNV.setText("Tìm kiếm");
        btnTimKiemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemNVActionPerformed(evt);
            }
        });

        btnTaiKhoan.setBackground(new java.awt.Color(0, 153, 153));
        btnTaiKhoan.setText("Tài khoản");
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });

        btnHoTro.setBackground(new java.awt.Color(0, 153, 0));
        btnHoTro.setText("Hỗ trợ");
        btnHoTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoTroActionPerformed(evt);
            }
        });

        btnDSTacGai.setText("Danh sách");
        btnDSTacGai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSTacGaiActionPerformed(evt);
            }
        });

        btnTimKiemTG.setText("Tìm kiếm");
        btnTimKiemTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemTGActionPerformed(evt);
            }
        });

        btnNXB.setBackground(new java.awt.Color(255, 102, 0));
        btnNXB.setText("Nhà xuất bản");
        btnNXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNXBMouseClicked(evt);
            }
        });

        btnDanhSachNXB.setText("Danh sách");
        btnDanhSachNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachNXBActionPerformed(evt);
            }
        });

        btnTimKiemNXB.setText("Tìm kiếm");
        btnTimKiemNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemNXBActionPerformed(evt);
            }
        });

        btnTimKiemSach.setText("Tìm kiếm sách");
        btnTimKiemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemSachActionPerformed(evt);
            }
        });

        btnSanPhamKhac.setText("Sản phẩm khác");
        btnSanPhamKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamKhacActionPerformed(evt);
            }
        });

        btnTimKiemSPKhac.setText("Tìm kiếm sản phẩm khác");
        btnTimKiemSPKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemSPKhacActionPerformed(evt);
            }
        });

        btnTimKiemKH.setText("Tìm Kiếm");
        btnTimKiemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemKHActionPerformed(evt);
            }
        });

        btnLoaiSP.setBackground(new java.awt.Color(255, 102, 0));
        btnLoaiSP.setText("Loại sản phẩm");
        btnLoaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoaiSPMouseClicked(evt);
            }
        });
        btnLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSPActionPerformed(evt);
            }
        });

        btnDSLoaiSP.setText("Danh sách");
        btnDSLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSLoaiSPActionPerformed(evt);
            }
        });

        btnTimKiemLSP.setText("Tìm kiếm");
        btnTimKiemLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemLSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDSHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDangKyCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDSNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTKDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTKSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTKKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDSNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTacGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDSTacGai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTimKiemNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTimKiemNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTimKiemTG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDanhSachNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTimKiemNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTimKiemSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSanPhamKhac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTimKiemSPKhac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTimKiemKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDMSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDSLoaiSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTimKiemLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHoTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLoaiSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(btnDSKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addComponent(btnDMSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSach, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSanPhamKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTimKiemSPKhac)
                .addGap(0, 0, 0)
                .addComponent(btnHoaDon)
                .addGap(0, 0, 0)
                .addComponent(btnLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDSHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDangKyCa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDSNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTimKiemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTKKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTKDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTKSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDSKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhaCungCap)
                .addGap(0, 0, 0)
                .addComponent(btnDSNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTimKiemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDSTacGai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTimKiemTG, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDanhSachNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTimKiemNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDSLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTimKiemLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHoTro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnLapHoaDon.hide();
        btnSach.hide();
        btnDSHoaDon.hide();
        btnDangKyCa.hide();
        btnDSNhanVien.hide();
        btnTKDoanhThu.hide();
        btnTKSanPham.hide();
        btnTKKhachHang.hide();
        btnDSNhaCungCap.hide();
        btnNhapHang.hide();
        btnTimKiemNCC.hide();
        btnDSKhachHang.hide();
        btnTimKiemNV.hide();
        btnDSTacGai.hide();
        btnTimKiemTG.hide();
        btnDanhSachNXB.hide();
        btnTimKiemNXB.hide();
        btnTimKiemSach.hide();
        btnSanPhamKhac.hide();
        btnTimKiemSPKhac.hide();
        btnTimKiemKH.hide();
        btnDSLoaiSP.hide();
        btnTimKiemLSP.hide();

        pnlChuongTrinh.setBackground(new java.awt.Color(0, 102, 102));
        pnlChuongTrinh.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlChuongTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnlChuongTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDMSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDMSanPhamActionPerformed

    private void btnSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSachActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new View_danhmucsach());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnSachActionPerformed

    private void btnTimKiemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemNCCActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlTimKiemNCC());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnTimKiemNCCActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlDSTaiKhoan());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTacGiaActionPerformed

    private void btnTimKiemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemSachActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new pnlTimKiemSach());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnTimKiemSachActionPerformed

    private void btnSanPhamKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamKhacActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new View_sanphamkhac());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnSanPhamKhacActionPerformed

    private void btnTimKiemSPKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemSPKhacActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new pnlTimKiemSPKhac());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnTimKiemSPKhacActionPerformed

    private void btnTKDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKDoanhThuMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTKDoanhThuMouseClicked

    private void btnTKDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKDoanhThuActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlThongKeDoanhThu());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnTKDoanhThuActionPerformed

    private void btnTKKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKKhachHangActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlThongKeKH());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnTKKhachHangActionPerformed

    private void btnTKSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKSanPhamActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlThongKeSanPham());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnTKSanPhamActionPerformed

    private void btnDSNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSNhaCungCapActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlDSNhaCungCap());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnDSNhaCungCapActionPerformed

    private void btnDangKyCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyCaActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlCaLamViec());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
        
    }//GEN-LAST:event_btnDangKyCaActionPerformed
    
    private void btnDSHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSNhanVienActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlDSHoaDon());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnDSNhanVienActionPerformed


    private void btnDSNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSNhanVienActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlDSNhanVien());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnDSNhanVienActionPerformed

    private void btnLapHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapHoaDonActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlLapHoaDonMoi());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.validate();
    }//GEN-LAST:event_btnLapHoaDonActionPerformed

    private void btnDSKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSKhachHangActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlDSKhachHang());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.validate();
    }//GEN-LAST:event_btnDSKhachHangActionPerformed

    private void btnTimKiemNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemNXBActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlTimKiemNXB());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.validate();
    }//GEN-LAST:event_btnTimKiemNXBActionPerformed

    private void btnTimKiemTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemTGActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlTimKiemTacGia());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.validate();
    }//GEN-LAST:event_btnTimKiemTGActionPerformed

    private void btnDanhSachNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachNXBActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlDSNhaXuatBan());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.validate();
    }//GEN-LAST:event_btnDanhSachNXBActionPerformed

    private void btnDSTacGaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSTacGaiActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlDSTacGia());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.validate();
    }//GEN-LAST:event_btnDSTacGaiActionPerformed

    private void btnDMSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMSanPhamMouseClicked
        // TODO add your handling code here:
        if(flagSP){
            btnSach.setVisible(flagSP);
            btnTimKiemSach.setVisible(flagSP);
            btnTimKiemSPKhac.setVisible(flagSP);
            btnSanPhamKhac.setVisible(flagSP);
            flagSP = false;
        }
        else{
            btnSach.hide();
            btnTimKiemSach.hide();
            btnSanPhamKhac.hide();
            btnTimKiemSPKhac.hide();
            
            flagSP = true;
        }
        
    }//GEN-LAST:event_btnDMSanPhamMouseClicked

    private void btnHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseClicked
        // TODO add your handling code here:
        if(flagHD){
            btnLapHoaDon.setVisible(flagHD);
            btnDSHoaDon.setVisible(flagHD);
            flagHD = false;
        }
        else{
            btnLapHoaDon.hide();
            btnDSHoaDon.hide();
            flagHD = true;
        }
    }//GEN-LAST:event_btnHoaDonMouseClicked

    private void btnQLNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNhanVienMouseClicked
        // TODO add your handling code here:
        if(flagNV){
            btnDangKyCa.setVisible(flagNV);
            btnDSNhanVien.setVisible(flagNV);
            btnTimKiemNV.setVisible(flagNV);
            
            btnTKDoanhThu.setVisible(flagNV);
            btnTKKhachHang.setVisible(flagNV);
            btnTKSanPham.setVisible(flagNV);
            flagNV = false;
        }
        else{
            btnDangKyCa.hide();
            btnDSNhanVien.hide();
            btnTimKiemNV.hide();
            btnTKDoanhThu.hide();
            btnTKKhachHang.hide();
            btnTKSanPham.hide();
            flagNV = true;
        }
    }//GEN-LAST:event_btnQLNhanVienMouseClicked

    private void btnKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseClicked
        // TODO add your handling code here:
        if(flagKH){
            btnDSKhachHang.setVisible(flagKH);
            btnTimKiemKH.setVisible(flagKH);
            flagKH = false;
        }
        else{
            btnDSKhachHang.hide();
            btnTimKiemKH.hide();
            flagKH = true;
        }
    }//GEN-LAST:event_btnKhachHangMouseClicked

    private void btnNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhaCungCapMouseClicked
        // TODO add your handling code here:
        if(flagNCC){
            btnDSNhaCungCap.setVisible(flagNCC);
            btnTimKiemNCC.setVisible(flagNCC);
            btnNhapHang.setVisible(flagNCC);
            flagNCC = false;
        }
        else{
            btnDSNhaCungCap.hide();
            btnTimKiemNCC.hide();
            btnNhapHang.hide();
            flagNCC = true;
        }
    }//GEN-LAST:event_btnNhaCungCapMouseClicked

    private void btnTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTacGiaMouseClicked
        // TODO add your handling code here:
        if(flagTG){
            btnDSTacGai.setVisible(flagTG);
            btnTimKiemTG.setVisible(flagTG);
            flagTG = false;
        }
        else{
            btnDSTacGai.hide();
            btnTimKiemTG.hide();
            flagTG = true;
        }
    }//GEN-LAST:event_btnTacGiaMouseClicked

    private void btnNXBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNXBMouseClicked
        // TODO add your handling code here:
        if(flagNXB){
            btnDanhSachNXB.setVisible(flagNXB);
            btnTimKiemNXB.setVisible(flagNXB);
            flagNXB = false;
        }
        else{
            btnDanhSachNXB.hide();
            btnTimKiemNXB.hide();
            flagNXB = true;
        }
    }//GEN-LAST:event_btnNXBMouseClicked

    private void btnTimKiemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemKHActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlTimKiemKH());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnTimKiemKHActionPerformed

    private void btnTimKiemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemNVActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new PnlTimKiemNhanVien());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnTimKiemNVActionPerformed

    private void btnLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoaiSPActionPerformed

    private void btnDSLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSLoaiSPActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new View_loaisanpham());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnDSLoaiSPActionPerformed

    private void btnTimKiemLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemLSPActionPerformed
        // TODO add your handling code here:
         pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new View_timkiemloaisanpham());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnTimKiemLSPActionPerformed

    private void btnLoaiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiSPMouseClicked
        // TODO add your handling code here:
        if(flagLSP){
            btnDSLoaiSP.setVisible(flagLSP);
            btnTimKiemLSP.setVisible(flagLSP);
            flagLSP = false;
        }
        else{
            btnDSLoaiSP.hide();
            btnTimKiemLSP.hide();
            flagLSP = true;
        }
    }//GEN-LAST:event_btnLoaiSPMouseClicked

    private void btnHoTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoTroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHoTroActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        // TODO add your handling code here:
        pnlChuongTrinh.removeAll();
        pnlChuongTrinh.add(new View_nhaphang());
        pnlChuongTrinh.repaint();
        pnlChuongTrinh.revalidate();
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void btnNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhaCungCapActionPerformed

    private void khoaflag(boolean  b){
       flagSP = b;
       flagHD = b;
       flagNV = b;
       flagKH = b;
       flagTK = b;
       flagNCC = b;
       flagTG = b;
       flagNXB = b;
       flagLSP = b;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IllegalArgumentException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ManHinhChinh().setVisible(true);
        });
    }

    public static javax.swing.JPanel getPnlChuongTrinh() {
        return pnlChuongTrinh;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDMSanPham;
    private javax.swing.JButton btnDSHoaDon;
    private javax.swing.JButton btnDSKhachHang;
    private javax.swing.JButton btnDSLoaiSP;
    private javax.swing.JButton btnDSNhaCungCap;
    private javax.swing.JButton btnDSNhanVien;
    private javax.swing.JButton btnDSTacGai;
    private javax.swing.JButton btnDangKyCa;
    private javax.swing.JButton btnDanhSachNXB;
    private javax.swing.JButton btnHoTro;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLapHoaDon;
    private javax.swing.JButton btnLoaiSP;
    private javax.swing.JButton btnNXB;
    private javax.swing.JButton btnNhaCungCap;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnQLNhanVien;
    private javax.swing.JButton btnSach;
    private javax.swing.JButton btnSanPhamKhac;
    private javax.swing.JButton btnTKDoanhThu;
    private javax.swing.JButton btnTKKhachHang;
    private javax.swing.JButton btnTKSanPham;
    private javax.swing.JButton btnTacGia;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnTimKiemKH;
    private javax.swing.JButton btnTimKiemLSP;
    private javax.swing.JButton btnTimKiemNCC;
    private javax.swing.JButton btnTimKiemNV;
    private javax.swing.JButton btnTimKiemNXB;
    private javax.swing.JButton btnTimKiemSPKhac;
    private javax.swing.JButton btnTimKiemSach;
    private javax.swing.JButton btnTimKiemTG;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTenTieuDe;
    private static javax.swing.JPanel pnlChuongTrinh;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTieuDe;
    // End of variables declaration//GEN-END:variables
    private boolean  flagSP = true;
    private boolean  flagHD = true;
    private boolean  flagNV = true;
    private boolean  flagKH = true;
    private boolean  flagTK = true;
    private boolean  flagNCC = true;
    private boolean  flagTG = true;
    private boolean  flagNXB = true;
    private boolean  flagLSP = true;
}
