/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.LoaiSanPhamDAO;
import dao.SanPhamDAO;
import entity.LoaiSanPham;
import entity.SanPham;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NHU NGOC
 */
public class pnlTimKiemSPKhac extends javax.swing.JPanel {
    private DefaultTableModel model;
    private SanPham sanpham;
    private ArrayList<SanPham> dsSanPham;
    private static final SanPhamDAO DAO = new SanPhamDAO();
    private static final LoaiSanPhamDAO LSPDAO = new LoaiSanPhamDAO();

    /**
     * Creates new form pnlTimKiemSPKhac
     */
    public pnlTimKiemSPKhac() {
        initComponents();
        loadTable();
    }
    private void clearTable(){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
    }
    /*
    "Mã sản phẩm", "Tên sản phẩm",
    "Loại sản phẩm", "Giá bán ",
    "Số lượng"
    */
    public void loadTable(){
        dsSanPham = DAO.timDanhSachSanPham();
        for(SanPham sp: dsSanPham){
            model.addRow(new Object[]{
            sp.getMa_SanPham(),sp.getTenSanPham(),
            sp.getLoaiSanPham().getLoaiSP(), sp.getLoaiSanPham().getTenLoai(),sp.getSoLuong()});
        }
    }
    public void loadTableTuDanhSach(ArrayList<SanPham> dsSanPham){
        //dsSanPham = DAO.timDanhSachSanPham();
        for(SanPham sp: dsSanPham){
            model.addRow(new Object[]{
            sp.getMa_SanPham(),sp.getTenSanPham(),
            sp.getLoaiSanPham().getLoaiSP(), sp.getLoaiSanPham().getTenLoai(),sp.getSoLuong()});
        }
    }

    public void hienThiThongBao(String thongBao, JTextField txt){
        JOptionPane.showMessageDialog(null, thongBao);
        if(txt == null)
            return;
        txt.requestFocus();
    }
    
    private void clearTextFields(){
        txtMaSP.setText("");
        txtTenSP.setText("");
        cbxLoaiSP.setSelectedIndex(0);
    }
    private void napDLVaoTextField(){
        int n = table.getSelectedRow();
        if(n == -1)
            return;
        ArrayList<SanPham> listSanPham = new ArrayList<>();
        listSanPham = DAO.timDanhSachSanPhamTheoMaSP(model.getValueAt(n, 0).toString());
        for(SanPham sp: listSanPham){
            txtMaSP.setText(model.getValueAt(n, 0).toString());
            
            txtTenSP.setText(sp.getTenSanPham());
            cbxLoaiSP.addItem(sp.getLoaiSanPham().getLoaiSP());
            cbxLoaiSP.setSelectedItem(sp.getLoaiSanPham().getLoaiSP());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        pnlTimSPKhac = new javax.swing.JPanel();
        pnlThongTinTimKiem = new javax.swing.JPanel();
        txtMaSP = new javax.swing.JTextField();
        lblLoaiSP = new javax.swing.JLabel();
        cbxLoaiSP = new javax.swing.JComboBox<>();
        lblMaSP = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        btnTimSPKhac = new javax.swing.JButton();
        btnXoaTrangSPKhac = new javax.swing.JButton();
        jScrollPaneSPKhac = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        pnlTieuDe.setBackground(new java.awt.Color(0, 153, 153));

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTieuDe.setText("TÌM KIẾM SẢN PHẨM");

        javax.swing.GroupLayout pnlTieuDeLayout = new javax.swing.GroupLayout(pnlTieuDe);
        pnlTieuDe.setLayout(pnlTieuDeLayout);
        pnlTieuDeLayout.setHorizontalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap(622, Short.MAX_VALUE)
                .addComponent(lblTieuDe)
                .addGap(540, 540, 540))
        );
        pnlTieuDeLayout.setVerticalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlThongTinTimKiem.setBackground(new java.awt.Color(204, 204, 204));
        pnlThongTinTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        lblLoaiSP.setText("Loại sản phẩm:");

        cbxLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Loại sản phẩm--", "1" }));

        lblMaSP.setText("Mã sản phẩm");

        lblTenSP.setText("Tên sản phẩm");

        javax.swing.GroupLayout pnlThongTinTimKiemLayout = new javax.swing.GroupLayout(pnlThongTinTimKiem);
        pnlThongTinTimKiem.setLayout(pnlThongTinTimKiemLayout);
        pnlThongTinTimKiemLayout.setHorizontalGroup(
            pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaSP)
                    .addComponent(lblTenSP))
                .addGap(65, 65, 65)
                .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtTenSP))
                .addGap(123, 123, 123)
                .addComponent(lblLoaiSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(cbxLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        pnlThongTinTimKiemLayout.setVerticalGroup(
            pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinTimKiemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaSP)
                    .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLoaiSP)
                        .addComponent(cbxLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenSP))
                .addGap(89, 89, 89))
        );

        btnTimSPKhac.setBackground(new java.awt.Color(204, 204, 204));
        btnTimSPKhac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.jpg"))); // NOI18N
        btnTimSPKhac.setText("Tìm kiếm");
        btnTimSPKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSPKhacActionPerformed(evt);
            }
        });

        btnXoaTrangSPKhac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eraser.png"))); // NOI18N
        btnXoaTrangSPKhac.setText("Xóa trắng");
        btnXoaTrangSPKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangSPKhacActionPerformed(evt);
            }
        });

        String[] heads = {
            "Mã sản phẩm", "Tên sản phẩm", "Loại sản phẩm", "Giá bán ", "Số lượng"
        };
        model = new DefaultTableModel(heads, 0);
        table.setModel(model);
        table.setGridColor(new java.awt.Color(0, 0, 0));
        table.setShowGrid(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPaneSPKhac.setViewportView(table);

        javax.swing.GroupLayout pnlTimSPKhacLayout = new javax.swing.GroupLayout(pnlTimSPKhac);
        pnlTimSPKhac.setLayout(pnlTimSPKhacLayout);
        pnlTimSPKhacLayout.setHorizontalGroup(
            pnlTimSPKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimSPKhacLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPaneSPKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 1219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimSPKhacLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTimSPKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimSPKhacLayout.createSequentialGroup()
                        .addComponent(btnTimSPKhac)
                        .addGap(48, 48, 48)
                        .addComponent(btnXoaTrangSPKhac)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimSPKhacLayout.createSequentialGroup()
                        .addComponent(pnlThongTinTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))))
        );
        pnlTimSPKhacLayout.setVerticalGroup(
            pnlTimSPKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimSPKhacLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(pnlThongTinTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlTimSPKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimSPKhac)
                    .addComponent(btnXoaTrangSPKhac))
                .addGap(30, 30, 30)
                .addComponent(jScrollPaneSPKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(14, Short.MAX_VALUE)
                    .addComponent(pnlTimSPKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 708, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(45, Short.MAX_VALUE)
                    .addComponent(pnlTimSPKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed

    private void btnTimSPKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSPKhacActionPerformed
        // TODO add your handling code here:
        ArrayList<SanPham> list = new ArrayList<>();
        if(!txtMaSP.getText().equals("") && !txtMaSP.getText().equals("")){
            list = DAO.timDanhSachSanPhamTheoMaSP(txtMaSP.getText());
            ArrayList<SanPham> temp = new ArrayList<>();
            for(SanPham sp: list){
                if(sp.getTenSanPham().toLowerCase().contains(txtMaSP.getText().toLowerCase()))
                    temp.add(sp);
            }
            clearTable();
            loadTableTuDanhSach(list);
            
        }
        else if(!txtTenSP.getText().equals("")){
            list = DAO.timDanhSachSanPhamTheoTenSP(txtTenSP.getText());
            clearTable();
            loadTableTuDanhSach(list);
        }
        else
            JOptionPane.showMessageDialog(null, "Chưa nhập thông tin");
    }//GEN-LAST:event_btnTimSPKhacActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        napDLVaoTextField();
        
    }//GEN-LAST:event_tableMouseClicked

    private void btnXoaTrangSPKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangSPKhacActionPerformed
        // TODO add your handling code here:
        clearTextFields();
    }//GEN-LAST:event_btnXoaTrangSPKhacActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimSPKhac;
    private javax.swing.JButton btnXoaTrangSPKhac;
    private javax.swing.JComboBox<String> cbxLoaiSP;
    private javax.swing.JScrollPane jScrollPaneSPKhac;
    private javax.swing.JLabel lblLoaiSP;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlThongTinTimKiem;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JPanel pnlTimSPKhac;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
