/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import dao.LoaiSanPhamDAO;
import dao.SachDAO;
import dao.SanPhamDAO;
import entity.LoaiSanPham;
import entity.NhaXuatBan;
import entity.Sach;
import entity.SanPham;
import entity.TacGia;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NHU NGOC
 */
public class pnlTimKiemSach extends javax.swing.JPanel {
    
    private DefaultTableModel model;
    private static final SachDAO sachDAO = new SachDAO();
    private static final SanPhamDAO spDAO = new SanPhamDAO();
    private static final LoaiSanPhamDAO lspDAO = new LoaiSanPhamDAO();
    private ArrayList<Sach> list = new ArrayList<>();
    /**
     * Creates new form pnlTimKiemSach
     */
    public pnlTimKiemSach() {
        initComponents();
        loadTable();
    }

    /*
    "Mã Sách","Tên sách", "Tác Giả", "Năm xuất bản", "Nhà Xuất Bản"
    */
    public void loadTable(){
        list = sachDAO.dsSach();
        
        for( Sach s: list){
            //System.out.println(s);
            model.addRow(new Object[]{
                s.getSanPham().getMa_SanPham(), s.getSanPham().getTenSanPham(),
                s.getTacGia().getTenTacGia(),
                s.getNamSanXuat(), s.getNhaXuatBan().getTenNXB()
            });
        }
    }
    public void loadTableTuDanhSach(ArrayList<Sach> list){
        for( Sach s: list){
            //System.out.println(s);
            model.addRow(new Object[]{
                s.getSanPham().getMa_SanPham(), s.getSanPham().getTenSanPham(),
                s.getTacGia().getTenTacGia(),
                s.getNamSanXuat(), s.getNhaXuatBan().getTenNXB()
            });
        }
    }
    
    private void clearTable(){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
    }
    private void moKhoaControls(boolean b){
        btnTimSach.setEnabled(b);
        
        btnXoaTrangSach.setEnabled(b);
        
    }
    
    
    public void napDLVaoTextfield(){
        int n = table.getSelectedRow();
        if(n == -1)
            return;
        ArrayList<Sach> list = new ArrayList<>();
        list = sachDAO.dsSachTheoMa(model.getValueAt(n, 0).toString());
        for(Sach s: list){
            txtMaSach.setText(table.getValueAt(n, 0).toString());
            txtTenSach.setText(s.getSanPham().getTenSanPham());
            cmbNhaXB.addItem(s.getNhaXuatBan().getTenNXB());
            cmbNhaXB.setSelectedItem(s.getNhaXuatBan().getTenNXB());
            
            txtTacGia.setText(s.getTacGia().getTenTacGia());
            txtNamXB.setText(String.valueOf(s.getNamSanXuat()));
        } 
    }
    
    private void clearTextFields(){
            txtMaSach.setText("");
            txtTenSach.setText("");
            cmbNhaXB.setSelectedIndex(0);
            txtTacGia.setText("");
            txtNamXB.setText("");
        }
    
    public void hienThiThongBao(String thongBao, JTextField txt){
        JOptionPane.showMessageDialog(null, thongBao);
        if(txt == null)
            return;
        txt.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlThongTinTimKiem8 = new javax.swing.JPanel();
        lblMaSach = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        lblNamXB = new javax.swing.JLabel();
        lblTacGia = new javax.swing.JLabel();
        txtTacGia = new javax.swing.JTextField();
        txtNamXB = new javax.swing.JTextField();
        lblTenSach = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        lblNhaXB = new javax.swing.JLabel();
        cmbNhaXB = new javax.swing.JComboBox<>();
        btnTimSach = new javax.swing.JButton();
        btnXoaTrangSach = new javax.swing.JButton();
        jScrollPaneSach = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        pnlTieuDe.setBackground(new java.awt.Color(0, 153, 153));

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTieuDe.setText("TÌM KIẾM SÁCH");

        javax.swing.GroupLayout pnlTieuDeLayout = new javax.swing.GroupLayout(pnlTieuDe);
        pnlTieuDe.setLayout(pnlTieuDeLayout);
        pnlTieuDeLayout.setHorizontalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTieuDe)
                .addGap(541, 541, 541))
        );
        pnlTieuDeLayout.setVerticalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(lblTieuDe)
                .addContainerGap())
        );

        pnlThongTinTimKiem8.setBackground(new java.awt.Color(204, 204, 204));
        pnlThongTinTimKiem8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaSach.setText("Mã sách:");

        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachtxtMaSachActionPerformed(evt);
            }
        });

        lblNamXB.setText("Năm xuất bản:");

        lblTacGia.setText("Tác giả:");

        txtTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTacGiatxtTacGiaActionPerformed(evt);
            }
        });

        lblTenSach.setText("Tên sách");

        lblNhaXB.setText("Nhà xuất bản");

        cmbNhaXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Nhà xuất bản--" }));

        javax.swing.GroupLayout pnlThongTinTimKiem8Layout = new javax.swing.GroupLayout(pnlThongTinTimKiem8);
        pnlThongTinTimKiem8.setLayout(pnlThongTinTimKiem8Layout);
        pnlThongTinTimKiem8Layout.setHorizontalGroup(
            pnlThongTinTimKiem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTimKiem8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlThongTinTimKiem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinTimKiem8Layout.createSequentialGroup()
                        .addComponent(lblTacGia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinTimKiem8Layout.createSequentialGroup()
                        .addGroup(pnlThongTinTimKiem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSach)
                            .addComponent(lblTenSach))
                        .addGap(31, 31, 31)
                        .addGroup(pnlThongTinTimKiem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtTenSach))))
                .addGap(125, 125, 125)
                .addGroup(pnlThongTinTimKiem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamXB)
                    .addComponent(lblNhaXB))
                .addGap(50, 50, 50)
                .addGroup(pnlThongTinTimKiem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNamXB, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(cmbNhaXB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnlThongTinTimKiem8Layout.setVerticalGroup(
            pnlThongTinTimKiem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTimKiem8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlThongTinTimKiem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaSach)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamXB)
                    .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinTimKiem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenSach)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNhaXB)
                    .addComponent(cmbNhaXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlThongTinTimKiem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTacGia)
                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnTimSach.setBackground(new java.awt.Color(204, 204, 204));
        btnTimSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.jpg"))); // NOI18N
        btnTimSach.setText("Tìm kiếm");
        btnTimSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSachActionPerformed(evt);
            }
        });

        btnXoaTrangSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eraser.png"))); // NOI18N
        btnXoaTrangSach.setText("Xóa trắng");
        btnXoaTrangSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangSachActionPerformed(evt);
            }
        });

        String[] heads =  {
            "Mã Sách","Tên sách", "Tác Giả", "Năm xuất bản", "Nhà Xuất Bản"
        };
        model = new DefaultTableModel(heads, 0);
        table.setModel(model);
        table.setGridColor(new java.awt.Color(0, 0, 0));
        table.setShowGrid(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPaneSach.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pnlThongTinTimKiem8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(273, 273, 273)))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTimSach)
                        .addGap(48, 48, 48)
                        .addComponent(btnXoaTrangSach)
                        .addGap(160, 160, 160))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pnlThongTinTimKiem8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimSach)
                    .addComponent(btnXoaTrangSach))
                .addGap(12, 12, 12)
                .addComponent(jScrollPaneSach, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaSachtxtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachtxtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachtxtMaSachActionPerformed

    private void txtTacGiatxtTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTacGiatxtTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTacGiatxtTacGiaActionPerformed

    private void btnTimSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSachActionPerformed
        // TODO add your handling code here:
        String ma = txtMaSach.getText();
        String tenSach = txtTenSach.getText();
        String tenNXB = cmbNhaXB.getSelectedItem().toString();
        String tenTacGia = txtTacGia.getText();
        int namXuatBan;
        if(txtNamXB.getText().equals(""))
            namXuatBan = 0;
        else 
            namXuatBan = Integer.valueOf(txtNamXB.getText().toString());
        
        ArrayList<Sach> listMa = new ArrayList<>();
        if(!ma.equals("") && tenSach.equals("")){
            System.out.println(ma);
            listMa = sachDAO.dsSachTheoMa(ma);
            //System.out.println(listMa);
            clearTable();
            loadTableTuDanhSach(listMa);
        }
        else if(!ma.equals("")&& !tenSach.equals("")){
            listMa = sachDAO.dsSachTheoMa(ma);
            ArrayList<Sach> listTen = new ArrayList<>();
            for(Sach s: listMa){
                if(s.getSanPham().getTenSanPham().toLowerCase().contains(tenSach.toLowerCase()))
                    listTen.add(s);
            }
            clearTable();
            loadTableTuDanhSach(listTen);
        }
        
//        if(!ma.isEmpty()){
//            list = sachDAO.dsSachTheoMa(ma);
//            
//            ArrayList<Sach> listTimKiem =   (ArrayList<Sach>) list.stream()
//                    .filter(sach->tenSach.isEmpty()||sach.getSanPham().getTenSanPham().contains(tenSach))
//                    .filter(sach->tenNXB.isEmpty()||sach.getNhaXuatBan().getTenNXB().contains(tenNXB))
//                    .filter(sach->tenTacGia.isEmpty()||sach.getTacGia().getTenTacGia().contains(tenTacGia))
//                    .collect(Collectors.toList());
//            clearTable();
//            loadTableTuDanhSach(listTimKiem);
//        }
        
        else 
            JOptionPane.showMessageDialog(this, "Nhap thong tin");
        //if()
    }//GEN-LAST:event_btnTimSachActionPerformed

    private void btnXoaTrangSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangSachActionPerformed
        // TODO add your handling code here:
        clearTextFields();
    }//GEN-LAST:event_btnXoaTrangSachActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        napDLVaoTextfield();
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimSach;
    private javax.swing.JButton btnXoaTrangSach;
    private javax.swing.JComboBox<String> cmbNhaXB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneSach;
    private javax.swing.JLabel lblMaSach;
    private javax.swing.JLabel lblNamXB;
    private javax.swing.JLabel lblNhaXB;
    private javax.swing.JLabel lblTacGia;
    private javax.swing.JLabel lblTenSach;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlThongTinTimKiem8;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
