/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.NhanVienDAO;
import entity.NhanVien;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NHU NGOC
 */
public class PnlTimKiemNhanVien extends javax.swing.JPanel {

    private NhanVienDAO nhanVienDAO;
    private DefaultTableModel tModel;

    /**
     * Creates new form pnlQLNhanVien
     */
    public PnlTimKiemNhanVien() {
        initComponents();
        docDLVaoTable();
    }
    private void docDLVaoTable() {
		ArrayList<NhanVien> listNV;
		nhanVienDAO = new NhanVienDAO();
		listNV = nhanVienDAO.getListNhanVien();
		for (NhanVien nv : listNV) {
			tModel.addRow(new Object[] { nv.getMaNV(), nv.getTenNV(), nv.getNgaySinh(), nv.getcCCD(), nv.getDiaChi(),
					nv.getsDT(), nv.getChucVu(), nv.getNvQuanLy().getMaNV() });
		}

	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        pnlThongTinNV = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        lblCCCD = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSNV = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1307, 740));

        pnlTieuDe.setBackground(new java.awt.Color(0, 153, 153));

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTieuDe.setText("Tìm kiếm nhân viên");

        javax.swing.GroupLayout pnlTieuDeLayout = new javax.swing.GroupLayout(pnlTieuDe);
        pnlTieuDe.setLayout(pnlTieuDeLayout);
        pnlTieuDeLayout.setHorizontalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTieuDe)
                .addGap(551, 551, 551))
        );
        pnlTieuDeLayout.setVerticalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(lblTieuDe)
                .addContainerGap())
        );

        pnlThongTinNV.setBackground(new java.awt.Color(204, 204, 204));
        pnlThongTinNV.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin tìm kiếm"));

        lblMaNV.setText("Mã nhân viên:");

        lblTenNV.setText("Tên nhân viên:");

        lblCCCD.setText("Số CCCD:");

        txtTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNVActionPerformed(evt);
            }
        });

        lblSDT.setText("Số điện thoại:");

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        txtCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCCDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongTinNVLayout = new javax.swing.GroupLayout(pnlThongTinNV);
        pnlThongTinNV.setLayout(pnlThongTinNVLayout);
        pnlThongTinNVLayout.setHorizontalGroup(
            pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinNVLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTenNV)
                    .addComponent(lblMaNV))
                .addGap(26, 26, 26)
                .addGroup(pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135)
                .addGroup(pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCCCD)
                    .addComponent(lblSDT))
                .addGap(28, 28, 28)
                .addGroup(pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        pnlThongTinNVLayout.setVerticalGroup(
            pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinNVLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaNV, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCCCD, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNV)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSDT)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        btnTim.setBackground(new java.awt.Color(153, 153, 153));
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.jpg"))); // NOI18N
        btnTim.setText("Tìm kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eraser.png"))); // NOI18N
        btnXoaTrang.setText("Xóa trắng");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        String[] heads = {
            "Mã NV", "Tên nhân viên", "Ngày sinh", "CCCD", "Địa chỉ", "Số điện thoại", "Chức vụ", "ID quản lý"
        };
        tModel = new DefaultTableModel(heads, 0);
        tblDSNV.setModel(tModel);
        tblDSNV.setModel(tModel);
        tblDSNV.setGridColor(new java.awt.Color(153, 153, 153));
        tblDSNV.setSelectionBackground(new java.awt.Color(0, 102, 204));
        tblDSNV.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblDSNV.setShowGrid(true);
        tblDSNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSNV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(pnlThongTinNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addComponent(btnTim)
                        .addGap(71, 71, 71)
                        .addComponent(btnXoaTrang)))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlThongTinNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTim)
                    .addComponent(btnXoaTrang))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNVActionPerformed
    
    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        if (txtMaNV.getText().isEmpty() && txtTenNV.getText().isEmpty() && txtSDT.getText().isEmpty() && txtCCCD.getText().isEmpty()) {
            removeAllData();
            docDLVaoTable();
            
	}
        else if (!txtMaNV.getText().isEmpty()){
            String maNV = txtMaNV.getText();
            ArrayList<NhanVien> listNV = nhanVienDAO.timNhanVienVoiMaNV(maNV);
		
            if (listNV.isEmpty()) {
		JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên này");
		return;
            }
            removeAllData();
            for(NhanVien nv : listNV){
            tModel.addRow(new Object[] { nv.getMaNV(), nv.getTenNV(), nv.getNgaySinh(), nv.getcCCD(), nv.getDiaChi(), nv.getsDT(), nv.getChucVu(), nv.getNvQuanLy().getMaNV()});
            }
            
        }
        else if (!txtTenNV.getText().isEmpty()){
            String tenNV = txtTenNV.getText();
            ArrayList<NhanVien> listNV = nhanVienDAO.timNhanVienVoiTenNV(tenNV);
		
            if (listNV.isEmpty()) {
		JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên này");
		return;
            }
            removeAllData();
            for(NhanVien nv : listNV){
            tModel.addRow(new Object[] { nv.getMaNV(), nv.getTenNV(), nv.getNgaySinh(), nv.getcCCD(), nv.getDiaChi(), nv.getsDT(), nv.getChucVu(), nv.getNvQuanLy().getMaNV()});
            }
            
        }
        else if (!txtSDT.getText().isEmpty()){
            String sDT = txtSDT.getText();
            ArrayList<NhanVien> listNV = nhanVienDAO.timNhanVienVoiSDT(sDT);
		
            if (listNV.isEmpty()) {
		JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên này");
		return;
            }
            removeAllData();
            for(NhanVien nv : listNV){
            tModel.addRow(new Object[] { nv.getMaNV(), nv.getTenNV(), nv.getNgaySinh(), nv.getcCCD(), nv.getDiaChi(), nv.getsDT(), nv.getChucVu(), nv.getNvQuanLy().getMaNV()});
            }
        }
        else if (!txtCCCD.getText().isEmpty()){
            String cCCD = txtCCCD.getText();
            ArrayList<NhanVien> listNV = nhanVienDAO.timNhanVienVoiCCCD(cCCD);
		
            if (listNV.isEmpty()) {
		JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên này");
		return;
            }
            removeAllData();
            for(NhanVien nv : listNV){
            tModel.addRow(new Object[] { nv.getMaNV(), nv.getTenNV(), nv.getNgaySinh(), nv.getcCCD(), nv.getDiaChi(), nv.getsDT(), nv.getChucVu(), nv.getNvQuanLy().getMaNV()});
            }
        }
        else if (!txtTenNV.getText().isEmpty() && !txtCCCD.getText().isEmpty()){
            String ten = txtTenNV.getText();
            String cCCD = txtCCCD.getText();
            ArrayList<NhanVien> listNV = nhanVienDAO.timNhanVienVoiMaVaTen(ten, cCCD);
		
            if (listNV.isEmpty()) {
		JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên này");
		return;
            }
            removeAllData();
            for(NhanVien nv : listNV){
            tModel.addRow(new Object[] { nv.getMaNV(), nv.getTenNV(), nv.getNgaySinh(), nv.getcCCD(), nv.getDiaChi(), nv.getsDT(), nv.getChucVu(), nv.getNvQuanLy().getMaNV()});
            }
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCCDActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        // TODO add your handling code here:
        clearTextFields();
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void tblDSNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSNVMouseClicked
        try {
            // TODO add your handling code here:
            napDLVaoTextField();
        } catch (Exception ex) {
            Logger.getLogger(PnlTimKiemNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tblDSNVMouseClicked
    
    public void clearTextFields() {
        txtMaNV.setText("");
        txtTenNV.setText("");
        txtCCCD.setText("");
        txtSDT.setText("");
    }
    public void removeAllData() {
		tModel.getDataVector().removeAllElements();
	}
    
    private void napDLVaoTextField() throws Exception {
	int n = tblDSNV.getSelectedRow();
	if (n == -1) {
		return;
	}
	ArrayList<NhanVien> listNV = new ArrayList<>();
	listNV = nhanVienDAO.timNhanVienVoiMaNV(tModel.getValueAt(n, 0).toString());
	for (NhanVien nv : listNV) {
            txtMaNV.setText(tModel.getValueAt(n, 0).toString());
            txtTenNV.setText(nv.getTenNV());
            txtCCCD.setText(nv.getcCCD());
            txtSDT.setText(nv.getsDT());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCCCD;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlThongTinNV;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JTable tblDSNV;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
